# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required
# xcode8 has jdk8
osx_image: xcode8
# Not technically required but suppresses 'Ruby' in Job status message.
language: java

os:
  - linux
  - osx

env:
  - BAZEL=0.13.0

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      OS=darwin
    else
      sysctl kernel.unprivileged_userns_clone=1
      OS=linux
    fi
    wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL}/bazel-${BAZEL}-installer-${OS}-x86_64.sh"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --worker_verbose \
      --verbose_failures \
      --test_output=errors \
      --genrule_strategy=sandboxed \
      --spawn_strategy=sandboxed \
      --worker_sandboxing \
      --local_resources=400,2,1.0 \
      --distinct_host_configuration=false \
      ...
